services:
  - type: web
    name: zaoga-church-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PAYNOW_INTEGRATION_ID
        sync: false
      - key: PAYNOW_INTEGRATION_KEY
        sync: false
      - key: TURNSTILE_SECRET_KEY
        sync: false
